/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.neotys.ascode.api.v2.client.api;

import com.neotys.ascode.api.v2.client.model.ArrayOfReservationDefinition;
import com.neotys.ascode.api.v2.client.model.ArrayOfZoneDefinition;
import com.neotys.ascode.api.v2.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for ResourcesApi
 */
@Ignore
public class ResourcesApiTest {

    private final ResourcesApi api = new ResourcesApi();

    /**
     * Lists reservations
     *
     * Lists the reservations.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReservationsTest() throws ApiException {
        String fromDateTime = null;
        String toDateTime = null;
        Integer limit = null;
        Integer offset = null;
        ArrayOfReservationDefinition response = api.getReservations(fromDateTime, toDateTime, limit, offset);

        // TODO: test validations
    }
    /**
     * List all zones
     *
     * Lists the zones.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getZonesTest() throws ApiException {
        ArrayOfZoneDefinition response = api.getZones();

        // TODO: test validations
    }
}
