/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.neotys.ascode.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * TestDefinition
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-09-05T15:48:08.071+02:00[Europe/Paris]")
public class TestDefinition {

  @SerializedName("id")
  private String id = null;
  
  @SerializedName("name")
  private String name = null;
  
  @SerializedName("description")
  private String description = null;
  
  @SerializedName("author")
  private String author = null;
  
  /**
   * Reason that caused the test to end.
   */
  @JsonAdapter(TerminationReasonEnum.Adapter.class)
  public enum TerminationReasonEnum {
    
    POLICY("POLICY"),
    VARIABLE("VARIABLE"),
    MANUAL("MANUAL"),
    LG_AVAILABILITY("LG_AVAILABILITY"),
    LICENSE("LICENSE"),
    UNKNOWN("UNKNOWN");

    private String value;

    TerminationReasonEnum(String value) {
      this.value = value;
    }
    
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    
    public static TerminationReasonEnum fromValue(String text) {
      for (TerminationReasonEnum b : TerminationReasonEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    
    public static class Adapter extends TypeAdapter<TerminationReasonEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TerminationReasonEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TerminationReasonEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TerminationReasonEnum.fromValue(String.valueOf(value));
      }
    }
  }
  
  @SerializedName("terminationReason")
  private TerminationReasonEnum terminationReason = null;
  
  @SerializedName("lgCount")
  private Integer lgCount = null;
  
  @SerializedName("project")
  private String project = null;
  
  @SerializedName("scenario")
  private String scenario = null;
  
  /**
   * Status of the test.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    
    STARTING("STARTING"),
    RUNNING("RUNNING"),
    TERMINATED("TERMINATED"),
    UNKNOWN("UNKNOWN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }
  
  @SerializedName("status")
  private StatusEnum status = null;
  
  /**
   * Quality status of the test.
   */
  @JsonAdapter(QualityStatusEnum.Adapter.class)
  public enum QualityStatusEnum {
    
    PASSED("PASSED"),
    FAILED("FAILED"),
    COMPUTING("COMPUTING"),
    UNKNOWN("UNKNOWN");

    private String value;

    QualityStatusEnum(String value) {
      this.value = value;
    }
    
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    
    public static QualityStatusEnum fromValue(String text) {
      for (QualityStatusEnum b : QualityStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    
    public static class Adapter extends TypeAdapter<QualityStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final QualityStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public QualityStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return QualityStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }
  
  @SerializedName("qualityStatus")
  private QualityStatusEnum qualityStatus = null;
  
  @SerializedName("startDate")
  private Long startDate = null;
  
  @SerializedName("endDate")
  private Long endDate = null;
  
  @SerializedName("duration")
  private Long duration = null;
  
  public TestDefinition id(String id) {
    this.id = id;
    return this;
  }

  
  /**
  * Unique identifier of the test.
  * @return id
  **/
  
  
  @Schema(description = "Unique identifier of the test.")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  
  public TestDefinition name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * Name of the test.
  * @return name
  **/
  
  
  @Schema(description = "Name of the test.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public TestDefinition description(String description) {
    this.description = description;
    return this;
  }

  
  /**
  * Description of the test.
  * @return description
  **/
  
  
  @Schema(description = "Description of the test.")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  
  public TestDefinition author(String author) {
    this.author = author;
    return this;
  }

  
  /**
  * First and Last name of the person who launched the test.
  * @return author
  **/
  
  
  @Schema(description = "First and Last name of the person who launched the test.")
  public String getAuthor() {
    return author;
  }
  public void setAuthor(String author) {
    this.author = author;
  }
  
  public TestDefinition terminationReason(TerminationReasonEnum terminationReason) {
    this.terminationReason = terminationReason;
    return this;
  }

  
  /**
  * Reason that caused the test to end.
  * @return terminationReason
  **/
  
  
  @Schema(description = "Reason that caused the test to end.")
  public TerminationReasonEnum getTerminationReason() {
    return terminationReason;
  }
  public void setTerminationReason(TerminationReasonEnum terminationReason) {
    this.terminationReason = terminationReason;
  }
  
  public TestDefinition lgCount(Integer lgCount) {
    this.lgCount = lgCount;
    return this;
  }

  
  /**
  * Total number of Load Generators used in the test.
  * @return lgCount
  **/
  
  
  @Schema(description = "Total number of Load Generators used in the test.")
  public Integer getLgCount() {
    return lgCount;
  }
  public void setLgCount(Integer lgCount) {
    this.lgCount = lgCount;
  }
  
  public TestDefinition project(String project) {
    this.project = project;
    return this;
  }

  
  /**
  * Name of the project.
  * @return project
  **/
  
  
  @Schema(description = "Name of the project.")
  public String getProject() {
    return project;
  }
  public void setProject(String project) {
    this.project = project;
  }
  
  public TestDefinition scenario(String scenario) {
    this.scenario = scenario;
    return this;
  }

  
  /**
  * Name of the scenario.
  * @return scenario
  **/
  
  
  @Schema(description = "Name of the scenario.")
  public String getScenario() {
    return scenario;
  }
  public void setScenario(String scenario) {
    this.scenario = scenario;
  }
  
  public TestDefinition status(StatusEnum status) {
    this.status = status;
    return this;
  }

  
  /**
  * Status of the test.
  * @return status
  **/
  
  
  @Schema(description = "Status of the test.")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }
  
  public TestDefinition qualityStatus(QualityStatusEnum qualityStatus) {
    this.qualityStatus = qualityStatus;
    return this;
  }

  
  /**
  * Quality status of the test.
  * @return qualityStatus
  **/
  
  
  @Schema(description = "Quality status of the test.")
  public QualityStatusEnum getQualityStatus() {
    return qualityStatus;
  }
  public void setQualityStatus(QualityStatusEnum qualityStatus) {
    this.qualityStatus = qualityStatus;
  }
  
  public TestDefinition startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

  
  /**
  * Timestamp when the test started.
  * @return startDate
  **/
  
  
  @Schema(description = "Timestamp when the test started.")
  public Long getStartDate() {
    return startDate;
  }
  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }
  
  public TestDefinition endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

  
  /**
  * Timestamp when the test ended.
  * @return endDate
  **/
  
  
  @Schema(description = "Timestamp when the test ended.")
  public Long getEndDate() {
    return endDate;
  }
  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }
  
  public TestDefinition duration(Long duration) {
    this.duration = duration;
    return this;
  }

  
  /**
  * Test duration in seconds.
  * @return duration
  **/
  
  
  @Schema(description = "Test duration in seconds.")
  public Long getDuration() {
    return duration;
  }
  public void setDuration(Long duration) {
    this.duration = duration;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestDefinition testDefinition = (TestDefinition) o;
    return Objects.equals(this.id, testDefinition.id) &&
        Objects.equals(this.name, testDefinition.name) &&
        Objects.equals(this.description, testDefinition.description) &&
        Objects.equals(this.author, testDefinition.author) &&
        Objects.equals(this.terminationReason, testDefinition.terminationReason) &&
        Objects.equals(this.lgCount, testDefinition.lgCount) &&
        Objects.equals(this.project, testDefinition.project) &&
        Objects.equals(this.scenario, testDefinition.scenario) &&
        Objects.equals(this.status, testDefinition.status) &&
        Objects.equals(this.qualityStatus, testDefinition.qualityStatus) &&
        Objects.equals(this.startDate, testDefinition.startDate) &&
        Objects.equals(this.endDate, testDefinition.endDate) &&
        Objects.equals(this.duration, testDefinition.duration);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name, description, author, terminationReason, lgCount, project, scenario, status, qualityStatus, startDate, endDate, duration);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestDefinition {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    terminationReason: ").append(toIndentedString(terminationReason)).append("\n");
    sb.append("    lgCount: ").append(toIndentedString(lgCount)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    scenario: ").append(toIndentedString(scenario)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    qualityStatus: ").append(toIndentedString(qualityStatus)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



