version: '3'

services:
   mysql-ushahidi:
     container_name: ushaihidi-mysql
     image: neotys/cpv-mysql:1.5
     restart: always
     ports:
        - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: cpvprivate
     networks:
       - cpv

   ushahidi:
     container_name: ushaihidi
     depends_on:
       - mysql-ushahidi
     image: neotys/cpv-ushahidi:1.5
     restart: always
     ports:
        - "80:80"
     links:
        - mysql-ushahidi:mysql-ushahidi
     networks:
       - cpv

networks:
  cpv:
    external:
      name: cpv
