/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.neotys.ascode.api.v2.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ElementValues
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-02T07:51:59.064Z[GMT]")
public class ElementValues {
  @SerializedName("count")
  private Long count = null;

  @SerializedName("elementPerSecond")
  private Float elementPerSecond = null;

  @SerializedName("minDuration")
  private Long minDuration = null;

  @SerializedName("maxDuration")
  private Long maxDuration = null;

  @SerializedName("sumDuration")
  private Long sumDuration = null;

  @SerializedName("avgDuration")
  private Float avgDuration = null;

  @SerializedName("minTTFB")
  private Long minTTFB = null;

  @SerializedName("maxTTFB")
  private Long maxTTFB = null;

  @SerializedName("sumTTFB")
  private Long sumTTFB = null;

  @SerializedName("avgTTFB")
  private Float avgTTFB = null;

  @SerializedName("sumDownloadedBytes")
  private Long sumDownloadedBytes = null;

  @SerializedName("downloadedBytesPerSecond")
  private Float downloadedBytesPerSecond = null;

  @SerializedName("successCount")
  private Long successCount = null;

  @SerializedName("successPerSecond")
  private Float successPerSecond = null;

  @SerializedName("successRate")
  private Float successRate = null;

  @SerializedName("failureCount")
  private Long failureCount = null;

  @SerializedName("failurePerSecond")
  private Float failurePerSecond = null;

  @SerializedName("failureRate")
  private Float failureRate = null;

  @SerializedName("percentile50")
  private Float percentile50 = null;

  @SerializedName("percentile90")
  private Float percentile90 = null;

  @SerializedName("percentile95")
  private Float percentile95 = null;

  @SerializedName("percentile99")
  private Float percentile99 = null;

  public ElementValues count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * Count statistics are the number of full executions of an element of a User Path. If the element is interrupted (because of error or end of test), then the count number is not incremented.
   * @return count
  **/
  @Schema(description = "Count statistics are the number of full executions of an element of a User Path. If the element is interrupted (because of error or end of test), then the count number is not incremented.")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public ElementValues elementPerSecond(Float elementPerSecond) {
    this.elementPerSecond = elementPerSecond;
    return this;
  }

   /**
   * Number of iterations of the element per second.
   * @return elementPerSecond
  **/
  @Schema(description = "Number of iterations of the element per second.")
  public Float getElementPerSecond() {
    return elementPerSecond;
  }

  public void setElementPerSecond(Float elementPerSecond) {
    this.elementPerSecond = elementPerSecond;
  }

  public ElementValues minDuration(Long minDuration) {
    this.minDuration = minDuration;
    return this;
  }

   /**
   * Shortest response time, in milliseconds.
   * @return minDuration
  **/
  @Schema(description = "Shortest response time, in milliseconds.")
  public Long getMinDuration() {
    return minDuration;
  }

  public void setMinDuration(Long minDuration) {
    this.minDuration = minDuration;
  }

  public ElementValues maxDuration(Long maxDuration) {
    this.maxDuration = maxDuration;
    return this;
  }

   /**
   * Longest response time, in milliseconds.
   * @return maxDuration
  **/
  @Schema(description = "Longest response time, in milliseconds.")
  public Long getMaxDuration() {
    return maxDuration;
  }

  public void setMaxDuration(Long maxDuration) {
    this.maxDuration = maxDuration;
  }

  public ElementValues sumDuration(Long sumDuration) {
    this.sumDuration = sumDuration;
    return this;
  }

   /**
   * Sum of response time of all iterations, in milliseconds.
   * @return sumDuration
  **/
  @Schema(description = "Sum of response time of all iterations, in milliseconds.")
  public Long getSumDuration() {
    return sumDuration;
  }

  public void setSumDuration(Long sumDuration) {
    this.sumDuration = sumDuration;
  }

  public ElementValues avgDuration(Float avgDuration) {
    this.avgDuration = avgDuration;
    return this;
  }

   /**
   * Average response time, in milliseconds.
   * @return avgDuration
  **/
  @Schema(description = "Average response time, in milliseconds.")
  public Float getAvgDuration() {
    return avgDuration;
  }

  public void setAvgDuration(Float avgDuration) {
    this.avgDuration = avgDuration;
  }

  public ElementValues minTTFB(Long minTTFB) {
    this.minTTFB = minTTFB;
    return this;
  }

   /**
   * Shortest time to first byte, in milliseconds.
   * @return minTTFB
  **/
  @Schema(description = "Shortest time to first byte, in milliseconds.")
  public Long getMinTTFB() {
    return minTTFB;
  }

  public void setMinTTFB(Long minTTFB) {
    this.minTTFB = minTTFB;
  }

  public ElementValues maxTTFB(Long maxTTFB) {
    this.maxTTFB = maxTTFB;
    return this;
  }

   /**
   * Longest time to first byte, in milliseconds.
   * @return maxTTFB
  **/
  @Schema(description = "Longest time to first byte, in milliseconds.")
  public Long getMaxTTFB() {
    return maxTTFB;
  }

  public void setMaxTTFB(Long maxTTFB) {
    this.maxTTFB = maxTTFB;
  }

  public ElementValues sumTTFB(Long sumTTFB) {
    this.sumTTFB = sumTTFB;
    return this;
  }

   /**
   * Sum of time to first byte of all iterations, in milliseconds.
   * @return sumTTFB
  **/
  @Schema(description = "Sum of time to first byte of all iterations, in milliseconds.")
  public Long getSumTTFB() {
    return sumTTFB;
  }

  public void setSumTTFB(Long sumTTFB) {
    this.sumTTFB = sumTTFB;
  }

  public ElementValues avgTTFB(Float avgTTFB) {
    this.avgTTFB = avgTTFB;
    return this;
  }

   /**
   * Average time to first byte, in milliseconds.
   * @return avgTTFB
  **/
  @Schema(description = "Average time to first byte, in milliseconds.")
  public Float getAvgTTFB() {
    return avgTTFB;
  }

  public void setAvgTTFB(Float avgTTFB) {
    this.avgTTFB = avgTTFB;
  }

  public ElementValues sumDownloadedBytes(Long sumDownloadedBytes) {
    this.sumDownloadedBytes = sumDownloadedBytes;
    return this;
  }

   /**
   * Total size of network traffic for the element, in bytes.
   * @return sumDownloadedBytes
  **/
  @Schema(description = "Total size of network traffic for the element, in bytes.")
  public Long getSumDownloadedBytes() {
    return sumDownloadedBytes;
  }

  public void setSumDownloadedBytes(Long sumDownloadedBytes) {
    this.sumDownloadedBytes = sumDownloadedBytes;
  }

  public ElementValues downloadedBytesPerSecond(Float downloadedBytesPerSecond) {
    this.downloadedBytesPerSecond = downloadedBytesPerSecond;
    return this;
  }

   /**
   * Average size of network traffic for the element, in bytes per seconds.
   * @return downloadedBytesPerSecond
  **/
  @Schema(description = "Average size of network traffic for the element, in bytes per seconds.")
  public Float getDownloadedBytesPerSecond() {
    return downloadedBytesPerSecond;
  }

  public void setDownloadedBytesPerSecond(Float downloadedBytesPerSecond) {
    this.downloadedBytesPerSecond = downloadedBytesPerSecond;
  }

  public ElementValues successCount(Long successCount) {
    this.successCount = successCount;
    return this;
  }

   /**
   * Count of succeeded iterations.
   * @return successCount
  **/
  @Schema(description = "Count of succeeded iterations.")
  public Long getSuccessCount() {
    return successCount;
  }

  public void setSuccessCount(Long successCount) {
    this.successCount = successCount;
  }

  public ElementValues successPerSecond(Float successPerSecond) {
    this.successPerSecond = successPerSecond;
    return this;
  }

   /**
   * Count of succeeded iterations per second.
   * @return successPerSecond
  **/
  @Schema(description = "Count of succeeded iterations per second.")
  public Float getSuccessPerSecond() {
    return successPerSecond;
  }

  public void setSuccessPerSecond(Float successPerSecond) {
    this.successPerSecond = successPerSecond;
  }

  public ElementValues successRate(Float successRate) {
    this.successRate = successRate;
    return this;
  }

   /**
   * Percentage of succeeded iterations out of count.
   * @return successRate
  **/
  @Schema(description = "Percentage of succeeded iterations out of count.")
  public Float getSuccessRate() {
    return successRate;
  }

  public void setSuccessRate(Float successRate) {
    this.successRate = successRate;
  }

  public ElementValues failureCount(Long failureCount) {
    this.failureCount = failureCount;
    return this;
  }

   /**
   * Count of failed iterations.
   * @return failureCount
  **/
  @Schema(description = "Count of failed iterations.")
  public Long getFailureCount() {
    return failureCount;
  }

  public void setFailureCount(Long failureCount) {
    this.failureCount = failureCount;
  }

  public ElementValues failurePerSecond(Float failurePerSecond) {
    this.failurePerSecond = failurePerSecond;
    return this;
  }

   /**
   * Count of failed iterations per second.
   * @return failurePerSecond
  **/
  @Schema(description = "Count of failed iterations per second.")
  public Float getFailurePerSecond() {
    return failurePerSecond;
  }

  public void setFailurePerSecond(Float failurePerSecond) {
    this.failurePerSecond = failurePerSecond;
  }

  public ElementValues failureRate(Float failureRate) {
    this.failureRate = failureRate;
    return this;
  }

   /**
   * Percentage of failed iterations out of count.
   * @return failureRate
  **/
  @Schema(description = "Percentage of failed iterations out of count.")
  public Float getFailureRate() {
    return failureRate;
  }

  public void setFailureRate(Float failureRate) {
    this.failureRate = failureRate;
  }

  public ElementValues percentile50(Float percentile50) {
    this.percentile50 = percentile50;
    return this;
  }

   /**
   * 50th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.
   * @return percentile50
  **/
  @Schema(description = "50th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.")
  public Float getPercentile50() {
    return percentile50;
  }

  public void setPercentile50(Float percentile50) {
    this.percentile50 = percentile50;
  }

  public ElementValues percentile90(Float percentile90) {
    this.percentile90 = percentile90;
    return this;
  }

   /**
   * 90th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.
   * @return percentile90
  **/
  @Schema(description = "90th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.")
  public Float getPercentile90() {
    return percentile90;
  }

  public void setPercentile90(Float percentile90) {
    this.percentile90 = percentile90;
  }

  public ElementValues percentile95(Float percentile95) {
    this.percentile95 = percentile95;
    return this;
  }

   /**
   * 95th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.
   * @return percentile95
  **/
  @Schema(description = "95th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.")
  public Float getPercentile95() {
    return percentile95;
  }

  public void setPercentile95(Float percentile95) {
    this.percentile95 = percentile95;
  }

  public ElementValues percentile99(Float percentile99) {
    this.percentile99 = percentile99;
    return this;
  }

   /**
   * 99th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.
   * @return percentile99
  **/
  @Schema(description = "99th percentile of the element duration, in milliseconds. Requires at least NeoLoad 7.1. Only available when test is terminated.")
  public Float getPercentile99() {
    return percentile99;
  }

  public void setPercentile99(Float percentile99) {
    this.percentile99 = percentile99;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementValues elementValues = (ElementValues) o;
    return Objects.equals(this.count, elementValues.count) &&
        Objects.equals(this.elementPerSecond, elementValues.elementPerSecond) &&
        Objects.equals(this.minDuration, elementValues.minDuration) &&
        Objects.equals(this.maxDuration, elementValues.maxDuration) &&
        Objects.equals(this.sumDuration, elementValues.sumDuration) &&
        Objects.equals(this.avgDuration, elementValues.avgDuration) &&
        Objects.equals(this.minTTFB, elementValues.minTTFB) &&
        Objects.equals(this.maxTTFB, elementValues.maxTTFB) &&
        Objects.equals(this.sumTTFB, elementValues.sumTTFB) &&
        Objects.equals(this.avgTTFB, elementValues.avgTTFB) &&
        Objects.equals(this.sumDownloadedBytes, elementValues.sumDownloadedBytes) &&
        Objects.equals(this.downloadedBytesPerSecond, elementValues.downloadedBytesPerSecond) &&
        Objects.equals(this.successCount, elementValues.successCount) &&
        Objects.equals(this.successPerSecond, elementValues.successPerSecond) &&
        Objects.equals(this.successRate, elementValues.successRate) &&
        Objects.equals(this.failureCount, elementValues.failureCount) &&
        Objects.equals(this.failurePerSecond, elementValues.failurePerSecond) &&
        Objects.equals(this.failureRate, elementValues.failureRate) &&
        Objects.equals(this.percentile50, elementValues.percentile50) &&
        Objects.equals(this.percentile90, elementValues.percentile90) &&
        Objects.equals(this.percentile95, elementValues.percentile95) &&
        Objects.equals(this.percentile99, elementValues.percentile99);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, elementPerSecond, minDuration, maxDuration, sumDuration, avgDuration, minTTFB, maxTTFB, sumTTFB, avgTTFB, sumDownloadedBytes, downloadedBytesPerSecond, successCount, successPerSecond, successRate, failureCount, failurePerSecond, failureRate, percentile50, percentile90, percentile95, percentile99);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElementValues {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    elementPerSecond: ").append(toIndentedString(elementPerSecond)).append("\n");
    sb.append("    minDuration: ").append(toIndentedString(minDuration)).append("\n");
    sb.append("    maxDuration: ").append(toIndentedString(maxDuration)).append("\n");
    sb.append("    sumDuration: ").append(toIndentedString(sumDuration)).append("\n");
    sb.append("    avgDuration: ").append(toIndentedString(avgDuration)).append("\n");
    sb.append("    minTTFB: ").append(toIndentedString(minTTFB)).append("\n");
    sb.append("    maxTTFB: ").append(toIndentedString(maxTTFB)).append("\n");
    sb.append("    sumTTFB: ").append(toIndentedString(sumTTFB)).append("\n");
    sb.append("    avgTTFB: ").append(toIndentedString(avgTTFB)).append("\n");
    sb.append("    sumDownloadedBytes: ").append(toIndentedString(sumDownloadedBytes)).append("\n");
    sb.append("    downloadedBytesPerSecond: ").append(toIndentedString(downloadedBytesPerSecond)).append("\n");
    sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
    sb.append("    successPerSecond: ").append(toIndentedString(successPerSecond)).append("\n");
    sb.append("    successRate: ").append(toIndentedString(successRate)).append("\n");
    sb.append("    failureCount: ").append(toIndentedString(failureCount)).append("\n");
    sb.append("    failurePerSecond: ").append(toIndentedString(failurePerSecond)).append("\n");
    sb.append("    failureRate: ").append(toIndentedString(failureRate)).append("\n");
    sb.append("    percentile50: ").append(toIndentedString(percentile50)).append("\n");
    sb.append("    percentile90: ").append(toIndentedString(percentile90)).append("\n");
    sb.append("    percentile95: ").append(toIndentedString(percentile95)).append("\n");
    sb.append("    percentile99: ").append(toIndentedString(percentile99)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
