/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.neotys.ascode.api.v3.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.neotys.ascode.api.v3.client.model.SLAElementDefinition;
import com.neotys.ascode.api.v3.client.model.SLAKPIDefinition;
import com.neotys.ascode.api.v3.client.model.SLAStatusDefinition;
import com.neotys.ascode.api.v3.client.model.ThresholdDefinition;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SLAPerTestResultDefinition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-01T07:09:13.021Z[GMT]")
public class SLAPerTestResultDefinition {
  @SerializedName("kpi")
  private SLAKPIDefinition kpi = null;

  @SerializedName("status")
  private SLAStatusDefinition status = null;

  @SerializedName("value")
  private Float value = null;

  @SerializedName("warningThreshold")
  private ThresholdDefinition warningThreshold = null;

  @SerializedName("failedThreshold")
  private ThresholdDefinition failedThreshold = null;

  @SerializedName("element")
  private SLAElementDefinition element = null;

  public SLAPerTestResultDefinition kpi(SLAKPIDefinition kpi) {
    this.kpi = kpi;
    return this;
  }

   /**
   * Get kpi
   * @return kpi
  **/
  @Schema(description = "")
  public SLAKPIDefinition getKpi() {
    return kpi;
  }

  public void setKpi(SLAKPIDefinition kpi) {
    this.kpi = kpi;
  }

  public SLAPerTestResultDefinition status(SLAStatusDefinition status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public SLAStatusDefinition getStatus() {
    return status;
  }

  public void setStatus(SLAStatusDefinition status) {
    this.status = status;
  }

  public SLAPerTestResultDefinition value(Float value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(description = "")
  public Float getValue() {
    return value;
  }

  public void setValue(Float value) {
    this.value = value;
  }

  public SLAPerTestResultDefinition warningThreshold(ThresholdDefinition warningThreshold) {
    this.warningThreshold = warningThreshold;
    return this;
  }

   /**
   * Get warningThreshold
   * @return warningThreshold
  **/
  @Schema(description = "")
  public ThresholdDefinition getWarningThreshold() {
    return warningThreshold;
  }

  public void setWarningThreshold(ThresholdDefinition warningThreshold) {
    this.warningThreshold = warningThreshold;
  }

  public SLAPerTestResultDefinition failedThreshold(ThresholdDefinition failedThreshold) {
    this.failedThreshold = failedThreshold;
    return this;
  }

   /**
   * Get failedThreshold
   * @return failedThreshold
  **/
  @Schema(description = "")
  public ThresholdDefinition getFailedThreshold() {
    return failedThreshold;
  }

  public void setFailedThreshold(ThresholdDefinition failedThreshold) {
    this.failedThreshold = failedThreshold;
  }

  public SLAPerTestResultDefinition element(SLAElementDefinition element) {
    this.element = element;
    return this;
  }

   /**
   * Get element
   * @return element
  **/
  @Schema(description = "")
  public SLAElementDefinition getElement() {
    return element;
  }

  public void setElement(SLAElementDefinition element) {
    this.element = element;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SLAPerTestResultDefinition slAPerTestResultDefinition = (SLAPerTestResultDefinition) o;
    return Objects.equals(this.kpi, slAPerTestResultDefinition.kpi) &&
        Objects.equals(this.status, slAPerTestResultDefinition.status) &&
        Objects.equals(this.value, slAPerTestResultDefinition.value) &&
        Objects.equals(this.warningThreshold, slAPerTestResultDefinition.warningThreshold) &&
        Objects.equals(this.failedThreshold, slAPerTestResultDefinition.failedThreshold) &&
        Objects.equals(this.element, slAPerTestResultDefinition.element);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kpi, status, value, warningThreshold, failedThreshold, element);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SLAPerTestResultDefinition {\n");
    
    sb.append("    kpi: ").append(toIndentedString(kpi)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    warningThreshold: ").append(toIndentedString(warningThreshold)).append("\n");
    sb.append("    failedThreshold: ").append(toIndentedString(failedThreshold)).append("\n");
    sb.append("    element: ").append(toIndentedString(element)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
